package com.example.eurekaclient.domain.constant;

public enum Code {
    NOT_READABLE,
    REQUEST_VALIDATION_ERROR,
    INVALID_SCOPE,
    USER_ALREADY_EXISTS,
    INVALID_IMAGE,
    UNAUTHORIZED,
    INVALID_CREDENTIALS,
    UNSUPPORTED_DATA_TYPE,
    FILE_DOWNLOAD_FAILED,
    USER_NOT_OWNER,
    NOT_FOUND, PAYLOAD_TOO_LARGE
}
